# Generated by Django 3.2.3 on 2021-05-28 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_utilisateur', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=100)),
                ('mot_de_passe', models.CharField(max_length=30)),
                ('nom', models.CharField(max_length=30)),
                ('prénom', models.CharField(max_length=30)),
                ('date_naissance', models.DateField()),
                ('tel', models.CharField(max_length=30)),
                ('adresse', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur_admin',
            fields=[
                ('utilisateur_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ESIGRAD.utilisateur')),
                ('status', models.CharField(max_length=30)),
            ],
            bases=('ESIGRAD.utilisateur',),
        ),
        migrations.CreateModel(
            name='Utilisateur_privilégié',
            fields=[
                ('utilisateur_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ESIGRAD.utilisateur')),
                ('status', models.CharField(max_length=30)),
            ],
            bases=('ESIGRAD.utilisateur',),
        ),
        migrations.CreateModel(
            name='Utilisateur_simple',
            fields=[
                ('utilisateur_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ESIGRAD.utilisateur')),
                ('status', models.CharField(max_length=30)),
            ],
            bases=('ESIGRAD.utilisateur',),
        ),
    ]
