# Generated by Django 3.2.3 on 2021-05-28 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ESIGRAD', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rubrique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_rub', models.CharField(max_length=30)),
                ('utilisateur_admin_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ESIGRAD.utilisateur_admin')),
            ],
        ),
        migrations.CreateModel(
            name='Répertoire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_rep', models.CharField(max_length=30)),
                ('propriétaire', models.CharField(max_length=30)),
                ('emplacement', models.CharField(max_length=30)),
                ('date_création', models.DateField()),
                ('rubrique_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ESIGRAD.rubrique')),
                ('utilisateur_admin_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ESIGRAD.utilisateur_admin')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=100)),
                ('date_envoie', models.DateField()),
                ('utilisateur_simple_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ESIGRAD.utilisateur_simple')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_doc', models.CharField(max_length=30)),
                ('taille', models.IntegerField(max_length=30)),
                ('type_doc', models.CharField(max_length=30)),
                ('propriétaire', models.CharField(max_length=30)),
                ('date_création', models.DateField()),
                ('emplacement', models.CharField(max_length=30)),
                ('répertoire_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ESIGRAD.répertoire')),
                ('utilisateur_privilégié_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ESIGRAD.utilisateur_privilégié')),
            ],
        ),
    ]
