# Generated by Django 3.2.3 on 2021-05-28 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ESIGRAD', '0004_auto_20210528_1208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateur',
            name='documents',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='rubriques',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='répertoires',
        ),
        migrations.AddField(
            model_name='document',
            name='emplacement',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='document',
            name='répertoire',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='ESIGRAD.répertoire'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='document',
            name='utilisateur_privilégié',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='ESIGRAD.utilisateur_privilégié'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='document',
            name='utilisateurs',
            field=models.ManyToManyField(related_name='documents', to='ESIGRAD.Utilisateur'),
        ),
        migrations.AddField(
            model_name='notification',
            name='utilisateur_simple',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='ESIGRAD.utilisateur_simple'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rubrique',
            name='utilisateur_admin',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='ESIGRAD.utilisateur_admin'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rubrique',
            name='utilisateurs',
            field=models.ManyToManyField(related_name='rubriques', to='ESIGRAD.Utilisateur'),
        ),
        migrations.AddField(
            model_name='répertoire',
            name='rubrique',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='ESIGRAD.rubrique'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='répertoire',
            name='utilisateur_admin',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='ESIGRAD.utilisateur_admin'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='répertoire',
            name='utilisateurs',
            field=models.ManyToManyField(related_name='répertoires', to='ESIGRAD.Utilisateur'),
        ),
    ]
