# Generated by Django 3.2.3 on 2021-05-28 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ESIGRAD', '0007_auto_20210528_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='utilisateurs',
            field=models.ManyToManyField(related_name='documents', to='ESIGRAD.Utilisateur'),
        ),
        migrations.AlterField(
            model_name='rubrique',
            name='utilisateurs',
            field=models.ManyToManyField(related_name='rubriques', to='ESIGRAD.Utilisateur'),
        ),
        migrations.AlterField(
            model_name='répertoire',
            name='utilisateurs',
            field=models.ManyToManyField(related_name='répertoires', to='ESIGRAD.Utilisateur'),
        ),
    ]
