# Generated by Django 3.2.3 on 2021-06-02 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ESIGRAD', '0010_auto_20210602_1432'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='type_doc',
        ),
        migrations.AlterField(
            model_name='document',
            name='fichier',
            field=models.FileField(null=True, upload_to='doc/'),
        ),
    ]
