# Generated by Django 3.2.3 on 2021-06-30 14:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ESIGRAD', '0019_alter_répertoire_date_création'),
    ]

    operations = [
        migrations.AlterField(
            model_name='répertoire',
            name='date_création',
            field=models.DateField(default=datetime.datetime(2021, 6, 30, 15, 47, 48, 308937)),
        ),
    ]
