# Generated by Django 3.2.3 on 2021-05-28 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ESIGRAD', '0002_document_notification_rubrique_répertoire'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='répertoire_ID',
            new_name='répertoire',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='utilisateur_privilégié_ID',
            new_name='utilisateur_privilégié',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='utilisateur_simple_ID',
            new_name='utilisateur_simple',
        ),
        migrations.RenameField(
            model_name='rubrique',
            old_name='utilisateur_admin_ID',
            new_name='utilisateur_admin',
        ),
        migrations.RenameField(
            model_name='répertoire',
            old_name='rubrique_ID',
            new_name='rubrique',
        ),
        migrations.RenameField(
            model_name='répertoire',
            old_name='utilisateur_admin_ID',
            new_name='utilisateur_admin',
        ),
    ]
