# Generated by Django 3.2.3 on 2021-05-28 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ESIGRAD', '0003_auto_20210528_1156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='emplacement',
        ),
        migrations.RemoveField(
            model_name='document',
            name='répertoire',
        ),
        migrations.RemoveField(
            model_name='document',
            name='utilisateur_privilégié',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='utilisateur_simple',
        ),
        migrations.RemoveField(
            model_name='rubrique',
            name='utilisateur_admin',
        ),
        migrations.RemoveField(
            model_name='répertoire',
            name='rubrique',
        ),
        migrations.RemoveField(
            model_name='répertoire',
            name='utilisateur_admin',
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='documents',
            field=models.ManyToManyField(blank=True, related_name='utilisateurs', to='ESIGRAD.Document'),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='rubriques',
            field=models.ManyToManyField(blank=True, related_name='utilisateurs', to='ESIGRAD.Rubrique'),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='répertoires',
            field=models.ManyToManyField(blank=True, related_name='utilisateurs', to='ESIGRAD.Répertoire'),
        ),
        migrations.AlterField(
            model_name='document',
            name='taille',
            field=models.IntegerField(),
        ),
    ]
