# Generated by Django 3.2.3 on 2021-05-28 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ESIGRAD', '0006_alter_rubrique_utilisateur_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='répertoire',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ESIGRAD.répertoire'),
        ),
        migrations.AlterField(
            model_name='document',
            name='utilisateur_privilégié',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ESIGRAD.utilisateur_privilégié'),
        ),
        migrations.AlterField(
            model_name='document',
            name='utilisateurs',
            field=models.ManyToManyField(null=True, related_name='documents', to='ESIGRAD.Utilisateur'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='utilisateur_simple',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ESIGRAD.utilisateur_simple'),
        ),
        migrations.AlterField(
            model_name='rubrique',
            name='utilisateurs',
            field=models.ManyToManyField(null=True, related_name='rubriques', to='ESIGRAD.Utilisateur'),
        ),
        migrations.AlterField(
            model_name='répertoire',
            name='rubrique',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ESIGRAD.rubrique'),
        ),
        migrations.AlterField(
            model_name='répertoire',
            name='utilisateur_admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ESIGRAD.utilisateur_admin'),
        ),
        migrations.AlterField(
            model_name='répertoire',
            name='utilisateurs',
            field=models.ManyToManyField(null=True, related_name='répertoires', to='ESIGRAD.Utilisateur'),
        ),
    ]
