# Generated by Django 3.2.3 on 2021-06-01 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ESIGRAD', '0008_auto_20210528_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='pdf',
            field=models.FileField(null=True, upload_to='documents'),
        ),
    ]
