# Generated by Django 3.2.3 on 2021-06-02 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ESIGRAD', '0009_document_pdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='pdf',
        ),
        migrations.AddField(
            model_name='document',
            name='fichier',
            field=models.FileField(null=True, upload_to='documents/'),
        ),
    ]
