# Generated by Django 3.2.3 on 2021-06-06 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ESIGRAD', '0011_auto_20210602_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='date_création',
            field=models.DateField(auto_now_add=True),
        ),
    ]
