# Generated by Django 3.2.3 on 2021-06-10 12:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ESIGRAD', '0012_alter_document_date_création'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rubrique',
            name='utilisateurs',
        ),
        migrations.RemoveField(
            model_name='répertoire',
            name='emplacement',
        ),
        migrations.RemoveField(
            model_name='répertoire',
            name='propriétaire',
        ),
        migrations.RemoveField(
            model_name='répertoire',
            name='utilisateur_admin',
        ),
        migrations.RemoveField(
            model_name='répertoire',
            name='utilisateurs',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='date_naissance',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='prénom',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='tel',
        ),
        migrations.AlterField(
            model_name='rubrique',
            name='nom_rub',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='répertoire',
            name='date_création',
            field=models.DateField(default=datetime.datetime(2021, 6, 10, 13, 29, 26, 346481)),
        ),
    ]
