# Generated by Django 3.2.4 on 2021-06-10 13:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ESIGRAD', '0013_auto_20210610_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='répertoire',
            name='date_création',
            field=models.DateField(default=datetime.datetime(2021, 6, 10, 14, 45, 23, 276401)),
        ),
    ]
